#!/usr/bin/sh

chroots=(21-chroot-system 22-chroot-lamp 23-chroot-aegir)
scripts=(10-bootstrap 20-chroot 99-clean-up)

# Transfer files from host
for script in ${chroots[@]}; do
    curl --remote-name $HTTPHOST$script
done
# Get and execute build scripts in order
for script in ${scripts[@]}; do
    curl --remote-name $HTTPHOST$script
#    sh $script
done
