#!/usr/bin/sh

packages="dash dhcpcd e2fsprogs gptfdisk licenses linux openssh pacman pciutils procps-ng syslinux sudo"
#packages="base dash gptfdisk openssh sudo syslinux"

cd /usr/bin

# Create new GPT disk
sgdisk -Z /dev/sda
sgdisk -n 1:0:0 -t 1:8300 /dev/sda
sgdisk --attributes=1:set:2 /dev/sda

# Create and mount partitions
mkfs.ext4 -q /dev/sda1
mount -o noatime /dev/sda1 /mnt

# Install basic packages and chroot into system
curl 'https://www.archlinux.org/mirrorlist/?country=all&protocol=http&ip_version=4&use_mirror_status=on' | sed 's/^#S/S/' > /etc/pacman.d/mirrorlist
pacstrap /mnt $packages
genfstab -p /mnt >> /mnt/etc/fstab
