#!/usr/bin/sh

cd /usr/bin

# Install and start nginx, MariabDB, and PHP
pacman --noconfirm --needed --sync nginx php-fpm mariadb
systemctl enable nginx.service php-fpm.service mysqld.service

# Initialise database
# DELETE FROM mysql.user WHERE User='';
# DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
# DROP DATABASE test;
# FLUSH PRIVILEGES;
