#!/usr/bin/sh

cd /usr/bin

# Install Apache, MariabDB, and PHP
pacman --noconfirm --needed --sync apache mariadb php php-apache php-gd

sed --in-place 's/^memory_limit.*$/memory_limit = 192M/'  /etc/php/php.ini
sed --in-place 's/^open_basedir.*$/open_basedir = /'      /etc/php/php.ini
sed --in-place 's/^date.timezone.*$/date.timezone = UTC/' /etc/php/php.ini

sed --in-place 's/^;extension=mysqli.so$/extension=mysqli.so/' /etc/php/php.ini
sed --in-place 's/^;extension=pdo_mysql.so$/extension=pdo_mysql.so/' /etc/php/php.ini
sed --in-place 's/^;extension=posix.so$/extension=posix.so/' /etc/php/php.ini

systemctl enable httpd
systemctl enable mysqld

systemctl start mysqld
echo -e '\n' 'y\n' 'root\nroot\n' '\n\n\n\n' | mysql_secure_installation
