#!/usr/bin/sh

# Install AUR package installer: yaourt
for pkg in package-query yaourt; do
    curl "https://aur.archlinux.org/packages/${pkg:0:2}/${pkg}/${pkg}.tar.gz" | tar xzf -
    (cd "${pkg}"; makepkg --asroot --syncdeps --install --noconfirm)
    rm -rf "${pkg}"
done

# Install Aegir's package dependencies
yaourt --sync --noconfirm php-composer drush-git

# Add mysql user for aegir
#mysql --user=root --password=root \
#    --execute="GRANT ALL PRIVILEGES ON *.* TO 'aegir_root'@'%' IDENTIFIED BY 'aegir_root' WITH GRANT OPTION;"

# Install Aegir
yaourt --sync --noconfirm aegir-provision
yaourt --sync --noconfirm aegir-hostmaster
#sudo -u aegir drush hostmaster-install \
#    --web_group=http \
#    --http_service_type=nginx \
#    --root=/usr/share/webapps/aegir \
#    --aegir_db_user=aegir_root \
#    --aegir_db_pass=aegir_root \
#    --aegir_host=localhost \
#    --client_email=james@jamesan.ca \
#    localhost

# Refresh LAMP stack
#systemctl daemon-reload
#systemctl reload nginx.service php-fpm.service mysqld.service

# Start Aegir queue daemon
#sudo -u aegir drush @hostmaster en hosting_queued --yes
#systemctl start aegir.service
